- src: jborean93.win_openssh
  version: v0.2.0
- name: informatiquecdc.win_pending_reboot
  src: informatiquecdc.win_pending_reboot
- name: jpmat296.upgrade-powershell
  src: https://github.com/jpmat296/ansible-upgrade-powershell
