---
- name: Force hostname vagranthost
  win_hostname:
    name: vagranthost
  register: hn_changed
- name: Reboot if hostname has changed
  win_reboot: {}
  when: hn_changed.reboot_required
- name: install and enable TLSv1.2 for Server 2008 and 2008 R2
  block:
  - name: enable TLSv1.2 support for Server 2008 and 2008 R2
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\{{ item.type }}
      name: '{{ item.property }}'
      data: '{{ item.value }}'
      type: dword
      state: present
    register: pri_personalise_tls_config
    loop:
    - type: Server
      property: Enabled
      value: 1
    - type: Server
      property: DisabledByDefault
      value: 0
    - type: Client
      property: Enabled
      value: 1
    - type: Client
      property: DisabledByDefault
      value: 0

  - name: reboot if TLS config was applied
    win_reboot:
    when: pri_personalise_tls_config is changed
  when: man_host_type == '2008-x86' or man_host_type == '2008-x64' or man_host_type == '2008r2'

- name: set show hidden files/folders and file extensions for the default user profile
  win_regedit:
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat
  loop:
  - name: Hidden
    data: 1
  - name: HideFileExt
    data: 0

- name: disable screensaver for Server 2008 for the default user profile
  win_regedit:
    path: HKLM:\ANSIBLE\Control Panel\Desktop
    name: '{{ item.name }}'
    data: '{{ item.value|default(omit) }}'
    type: string
    state: '{{ item.state }}'
    hive: C:\Users\Default\NTUSER.dat
  when: man_host_type == '2008-x86' or man_host_type == '2008-x64'
  loop:
  - name: ScreenSaveActive
    state: present
    value: 0
  - name: SCRNSAVE.EXE
    state: absent

- name: set This PC as the default view for Windows Explorer for the default user profile
  win_regedit:
    path: HKLM:\ANSIBLE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: LaunchTo
    data: 1
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat
  when:  # this is only valid for 2016/10+
  - man_host_type != '2008-x86'
  - man_host_type != '2008-x64'
  - man_host_type != '2008r2'
  - man_host_type != '2012'
  - man_host_type != '2012r2'

- name: set show hidden files/folders and file extensions for the current user profile
  win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
    state: present
  loop:
  - name: Hidden
    data: 1
  - name: HideFileExt
    data: 0

- name: disable screensaver for Server 2008 for the current user profile
  win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: '{{ item.name }}'
    data: '{{ item.value|default(omit) }}'
    type: string
    state: '{{ item.state }}'
  when: man_host_type == '2008-x86' or man_host_type == '2008-x64'
  loop:
  - name: ScreenSaveActive
    state: present
    value: 0
  - name: SCRNSAVE.EXE
    state: absent

- name: set This PC as the default view for Windows Explorer for the current user profile
  win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: LaunchTo
    data: 1
    type: dword
    state: present
  when:
  - man_host_type != '2008-x86'
  - man_host_type != '2008-x64'
  - man_host_type != '2008r2'
  - man_host_type != '2012'
  - man_host_type != '2012r2'

- name: disable automatic updates (prevents TrustedInstaller startup thrash on older images)
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoUpdate
    data: 1
    type: dword
    state: present

- name: install set Chocolatey packages
  win_chocolatey:
    name: '{{ man_personalize_choco_packages }}'
    ignore_checksums: yes
    state: present
  when:
  - man_personalize_choco_packages|count > 0
  - man_personalize_choco_packages[0] != ''
  become: yes
  vars:  # run with become as we aren't sure what packages the user has specified
    ansible_become_user: '{{ ansible_user }}'
    ansible_become_pass: '{{ ansible_password }}'

- name: install the VirtualBox Guest Additions
  include_tasks: virtualbox.yml
  when: man_provider == 'virtualbox'

- name: install the QEMU Guest Additions
  include_tasks: qemu.yml
  when: man_provider == 'qemu'
