---
# tasks file for sap_bip
- name: Ensure no reboot is pending
  win_pending_reboot: {}
  register: test_pending_reboot_result
- name: reboot if need
  win_reboot: {}
  when: test_pending_reboot_result.reboot_required
- name: Get BIP install files
  win_get_url:
    url: "{{ item }}"
    username: anonymous
    dest: C:/Users/{{ sap_bip_installer_username }}/Desktop/
    force: false
  async: 900
  loop: "{{ sap_bip_install_urls }}"
- name: Install winrar
  win_chocolatey:
    name: winrar
- name: Decompress BIP install files with winrar
  win_command: |
    "C:\Program Files\WinRAR\unrar" x -idq {{ sap_bip_install_urls[0] | basename }} bip_install/
  args:
    chdir: C:/Users/{{ sap_bip_installer_username }}/Desktop
    creates: C:/Users/{{ sap_bip_installer_username }}/Desktop/bip_install/ProductId.txt
  async: 1500
- import_tasks: my_response_ini.yml
- import_tasks: setup.yml
- import_tasks: firewall.yml
- import_tasks: services.yml
