---
- name: Ensure BIP services are stopped
  win_service:
    name: "{{ item }}"
    state: stopped
    start_mode: manual  # else services are restarted after reboot
  with_items:
    - BOEXI40Tomcat
    - BOEXI40AutomationFramework
    - BOEXI40Agent
    - BOEXI40BWPublisherService
    - BOEXI40SIA{{ sap_bip_sia_name }}
    - SQLANYs_SQLAnywhereForBI
